[package]
name = "png" # Name of the crate/package, why? because it has its own cargo.toml file
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# To use external dependencies 
# Syntax is "crate name = x.y.z" and x.y.z is the specific version of the crate
# Then, in your Rust code, you would use the use keyword to import items from the crate: "use argsv::{some_module, other_module}'
[dependencies]
#argsv = { path = "./lib/rust/argsv/" } # This is a crate/package, why? because it has its own cargo.toml file
                                       # The project, "argsv-rust," depends on this external crate...
                                       # before Rust used to import this using "extern crate argsv" but now you would list it here first and then in your source code you would use them like in "use argsv::parse_command"

#png = { path = "./lib/rust/png/" }

#libc = "0.2"
#flate2 = "1.0.28"
#lazy_static = "1.4.0"
